config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root 'home#index'

  resources :addresses
  resources :phones
  resources :contacts
  resources :kinds # resources cria 8 rotas de forma automática

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :contact
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :kind
  has_one :address
  has_many :phones

  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :phones, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: true
  validates :email, presence: true, length: { minimum: 5 }
end

app/models/kind.rb
class Kind < ActiveRecord::Base
  has_many :contacts
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :contact
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :set_options_for_select, only: [:new, :edit, :update, :create]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all.order(:name).page(params[:page]).per(15)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @contact.build_address
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contacts_path, notice: I18n.t('messages.created') }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contacts_path, notice: I18n.t('messages.updated') }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: I18n.t('messages.destroyed') }
      format.json { head :no_content }
    end
  end

  private
    def set_options_for_select
      @kind_options_for_select = Kind.all
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :kind_id, :rmk,
        address_attributes: [:street, :city, :state],
        phones_attributes: [:id, :phone, :_destroy])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  before_action :set_kind, only: [:show, :edit, :update, :destroy]

  # GET /kinds
  # GET /kinds.json
  def index
    @kinds = Kind.all
  end

  # GET /kinds/1
  # GET /kinds/1.json
  def show
  end

  # GET /kinds/new
  def new
    @kind = Kind.new
  end

  # GET /kinds/1/edit
  def edit
  end

  # POST /kinds
  # POST /kinds.json
  def create
    @kind = Kind.new(kind_params)

    respond_to do |format|
      if @kind.save
        format.html { redirect_to @kind, notice: 'Kind was successfully created.' }
        format.json { render :show, status: :created, location: @kind }
      else
        format.html { render :new }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kinds/1
  # PATCH/PUT /kinds/1.json
  def update
    respond_to do |format|
      if @kind.update(kind_params)
        format.html { redirect_to @kind, notice: 'Kind was successfully updated.' }
        format.json { render :show, status: :ok, location: @kind }
      else
        format.html { render :edit }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kinds/1
  # DELETE /kinds/1.json
  def destroy
    @kind.destroy
    respond_to do |format|
      format.html { redirect_to kinds_url, notice: 'Kind was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kind
      @kind = Kind.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kind_params
      params.require(:kind).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  ESTADOS_BRASILEIROS = [
    ["Acre", "AC"],
    ["Alagoas", "AL"],
    ["Amapá", "AP"],
    ["Amazonas", "AM"],
    ["Bahia", "BA"],
    ["Ceará", "CE"],
    ["Distrito Federal", "DF"],
    ["Espírito Santo", "ES"],
    ["Goiás", "GO"],
    ["Maranhão", "MA"],
    ["Mato Grosso", "MT"],
    ["Mato Grosso do Sul", "MS"],
    ["Minas Gerais", "MG"],
    ["Pará", "PA"],
    ["Paraíba", "PB"],
    ["Paraná", "PR"],
    ["Pernambuco", "PE"],
    ["Piauí", "PI"],
    ["Rio de Janeiro", "RJ"],
    ["Rio Grande do Norte", "RN"],
    ["Rio Grande do Sul", "RS"],
    ["Rondônia", "RO"],
    ["Roraima", "RR"],
    ["Santa Catarina", "SC"],
    ["São Paulo", "SP"],
    ["Sergipe", "SE"],
    ["Tocantins", "TO"]
  ]

  def options_for_states(selected)
    options_for_select(ESTADOS_BRASILEIROS, selected)
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact, html: { class: "dark-matter" }) do |f| %>
  <h1>New Contact</h1>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :kind_id %><br>
    <%= f.collection_select(:kind_id, @kind_options_for_select, :id, :description) %>
  </div>

  <%= f.fields_for :address do |address_fields| %>
    <div class="field">
      <%= address_fields.label :street %><br>
      <%= address_fields.text_field :street %>
    </div>

    <div class="field">
      <%= address_fields.label :city %><br>
      <%= address_fields.text_field :city %>
    </div>

    <div class="field">
      <%= address_fields.label :state %><br>
      <%= address_fields.select :state, options_for_states(@contact.address.state) %>
    </div>
  <% end %>

  <div id="phones">
    <%= f.fields_for :phones do |phones_fields| %>
      <%= render partial: "phone_fields", locals: { f: phones_fields } %>
    <% end %>

    <div class="field">
      <%= f.label :phones, "<span class='glyphicon glyphicon-phone-alt' aria-hidden='true'></span>".html_safe %><br>
      <%= link_to_add_association('[Adicionar Telefones]', f, :phones) %>
    </div>
    <br>
  </div>

  <div class="field">
    <%= f.label :rmk %><br>
    <%= f.text_area :rmk %>
  </div>

  <div class="field">
    <%= f.label " " %>
    <%= f.submit class: "btn btn-success" %>
    <%= link_to 'Back', contacts_path, class: "btn btn-primary" %>
  </div>

  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> Erros ocorreram:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/contacts/_phone_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class: "phone-field"%>
    <%= link_to_remove_association('Remover', f) %>
  </div>
</div>

app/views/contacts/edit.html.erb
<div class="dark-matter">
  <h1>Editing Contact</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @contact %> |
  <%= link_to 'Back', contacts_path %>
</div>

app/views/contacts/index.html.erb
<div class="dark-matter">
  <script>
    $.notify("<%= notice %>", "success")
  </script>
  
  <h1><%= "#{t('messages.listing')} #{@contacts.model.model_name.human(count: @contacts.count)}" %></h1>

  <table>
    <thead>
      <tr>
        <th><%= @contacts.model.human_attribute_name("name") %></th>
        <th><%= @contacts.model.human_attribute_name("email") %></th>
        <th><%= @contacts.model.human_attribute_name("kind") %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @contacts.each do |contact| %>
        <tr style="background: <%= cycle(' #394d00', '#020') %>">
          <td><%= contact.name %></td>
          <td><%= contact.email %></td>
          <td><%= contact.kind.description %></td>
          <td><%= link_to t('buttons.show'), contact %></td>
          <td><%= link_to t('buttons.edit'), edit_contact_path(contact) %></td>
          <td><%= link_to t('buttons.destroy'), contact, method: :delete, data: { confirm: t('messages.confirm') } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @contacts %> <br>
  <%= link_to t('buttons.new'), new_contact_path, class: "btn btn-success" %>
  <%= link_to t('buttons.home'), root_path, class: "btn btn-primary" %>
</siv>

app/views/contacts/new.html.erb
<%= render 'form' %>

app/views/contacts/show.html.erb
<div class="dark-matter">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @contact.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @contact.email %>
  </p>

  <p>
    <strong>Kind:</strong>
    <%= @contact.kind %>
  </p>

  <p>
    <strong>Rmk:</strong>
    <%= @contact.rmk %>
  </p>

  <%= link_to 'Edit', edit_contact_path(@contact) %> |
  <%= link_to 'Back', contacts_path %>
</div>

app/views/home/index.html.erb
<div class="dark-matter">
  <h1>Seja bem-vindo!</h1>
  <ul>
    <li><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> - <%= link_to "Tipos", kinds_path %></li>
    <li><span class="glyphicon glyphicon-phone-alt" aria-hidden="true"></span> - <%= link_to "Contatos", contacts_path %></li>
  </ul>
</div>

app/views/kinds/_form.html.erb
<%= form_for(@kind, html: { class: "dark-matter" }) do |f| %>
  <% if @kind.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kind.errors.count, "error") %> prohibited this kind from being saved:</h2>

      <ul>
      <% @kind.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h1>New Kind</h1>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.label " " %>
    <%= f.submit class: "btn btn-success"%>
    <%= link_to 'Back', kinds_path, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/kinds/edit.html.erb
<div class="dark-matter">
  <h1>Editing Kind</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @kind %> |
  <%= link_to 'Back', kinds_path %>
</div>

app/views/kinds/index.html.erb
<div class="dark-matter">
  <p id="notice"><%= notice %></p>

  <h1>Listing Kinds</h1>

  <table>
    <thead>
      <tr>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @kinds.each do |kind| %>
        <tr>
          <td><%= kind.description %></td>
          <td><%= link_to t('buttons.show'), kind %></td>
          <td><%= link_to t('buttons.edit'), edit_kind_path(kind) %></td>
          <td><%= link_to t('buttons.destroy'), kind, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to t('buttons.kind'), new_kind_path, class: "btn btn-success" %>
  <%= link_to t('buttons.home'), root_path, class: "btn btn-primary" %>
</div>

app/views/kinds/new.html.erb
<%= render 'form' %>

app/views/kinds/show.html.erb
<div class="dark-matter">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Description:</strong>
    <%= @kind.description %>
  </p>

  <%= link_to 'Edit', edit_kind_path(@kind) %> |
  <%= link_to 'Back', kinds_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ContactsNotebook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    params[:controller] %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%#= javascript_include_tag 'alert' %>
  <%= javascript_include_tag params[:controller] %>
  <%= csrf_meta_tags %>


</head>
<body>

<%= yield %>

</body>
</html>